default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: glennjamin
  password: 

development:
  <<: *default
  database: wolfr_development

test:
  <<: *default
  database: wolfr_test

production:
  <<: *default
  database: wolfr_production
  username: wolfr
  password: <%= ENV['WOLFR_DATABASE_PASSWORD'] %>
